### PR TITLE
Hebrew translation added

### PR DESCRIPTION
**Pull request by yarons**
Sorry for the delay.

Hoping that the generator has a good unicode support otherwise the text will be either garbled or reversed.

### CODE REVIEW

**Comment by ByteHamster** [comment]
Thanks! Could you please make the two pull requests a single one?

> Hoping that the generator has a good unicode support otherwise the text will be either garbled or reversed.

Looks like they all end up blank :( Looks like Lato does not support Hebrew characters. We might get a new font later, so I will keep this PR open and report back as soon as we have a new font.

**Comment by yarons** [comment]
These are the fonts which support Hebrew, I can either use one of them as excpetion or we can select one of them for all the other languages:
https://fonts.google.com/?subset=hebrew

I will merge them to one once we'll settle this, sorry for the trouble.

**Comment by ByteHamster** [comment]
Could you please check if the generated texts look okay? Also, please check for typos :)

**Comment by yarons** [comment]
Wonderful, thanks!

**Comment by ByteHamster** [comment]
Sorry, I messed up the commits a bit. I squashed everything together in the original pull request (https://github.com/AntennaPod/AntennaPod/pull/4299). I will close this PR without merging but your actual changes are included in the PR.

Thanks a lot for translating!

**Comment by yarons** [comment]
Thank you!

**Pull request closed without merging**
